version: '3'
services:
  clnt-prod:
    image: pablooliva/ch.ckl.st-client:latest
    container_name: chcklst-client
    restart: always
    command: nginx -g 'daemon off;'
    volumes:
      - /home/chcklst/client/nginx-logs:/etc/nginx/logs
    expose:
      - 80
    environment:
      VIRTUAL_HOST: ch.ckl.st
      LETSENCRYPT_HOST: ch.ckl.st
      LETSENCRYPT_EMAIL: pablo@qecept.com
networks:
  default:
    external:
      name: nginx-proxy
