version: '3'
services:
  clnt-prod:
    image: pablooliva/ch.ckl.st-client:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
      restart_policy:
        condition: on-failure
    command: nginx -g 'daemon off;'
    ports:
      - "80:80"