version: '3'

services:
  clnt-dev:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: chcklst-client-dev
    command: npm start
    volumes:
      - '.:/app'
    ports:
      - '4200:4200'
