FROM node:9.9.0 as build-stage
WORKDIR /app
COPY . /app
RUN npm install
RUN npm link @angular/cli
RUN npm run build

FROM nginx:1.15
COPY --from=build-stage /app/dist/ /usr/share/nginx/html
COPY --from=build-stage /app/nginx/nginx-custom.conf /etc/nginx/conf.d/default.conf
COPY --from=build-stage /app/nginx/ssl.conf /etc/nginx/conf.d/ssl.conf
COPY --from=build-stage /app/nginx/mime.types /etc/nginx/conf.d/mime.types
RUN mkdir -p /etc/nginx/logs
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]