version: '3'

networks:
  web:
    external: true

services:
  clnt-stage:
    build:
      context: .
    container_name: chcklst-client-stage
    command: nginx -g 'daemon off;'
    volumes:
      - './nginx/nginx-custom-local.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '8080:8080'
    networks:
      - web
