version: '3'
services:
  clnt-prod:
    image: pablooliva/ch.ckl.st-client:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1000M
      restart_policy:
        condition: on-failure
    command: nginx -g 'daemon off;'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/dhparam.pem:/etc/ssl/certs/dhparam.pem
      - /etc/letsencrypt/live/ch.ckl.st-0001/fullchain.pem:/etc/letsencrypt/live/ch.ckl.st/fullchain.pem
      - /etc/letsencrypt/live/ch.ckl.st-0001/privkey.pem:/etc/letsencrypt/live/ch.ckl.st/privkey.pem
      - /home/nginx-logs:/etc/nginx/logs
      - /data/letsencrypt:/data/letsencrypt