version: '3'
services:
  clnt-dev:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: npm start
    volumes:
      - .:/app
    ports:
      - "4200:4200"
  clnt-prod:
    image: pablooliva/ch.ckl.st-client:latest
    command: nginx -g 'daemon off;'
    ports:
      - "80:80"