version: '3'

networks:
  web:
    external: true

services:
  clnt-dev:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: chcklst-client
    command: npm start
    volumes:
      - '.:/app'
    ports:
      - '4200:4200'
  clnt-stage:
    image: 'pablooliva/ch.ckl.st-client:latest'
    command: nginx -g 'daemon off;'
    ports:
      - '8080:8080'
    volumes:
      - './nginx/nginx-custom-local.conf:/etc/nginx/conf.d/default.conf'
    networks:
      - web
