version: '3'
services:
  clnt-prod:
    image: pablooliva/ch.ckl.st-client:latest
    container_name: chcklst-client
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1000M
      restart_policy:
        condition: on-failure
    command: nginx -g 'daemon off;'
    volumes:
      - /home/chcklst/client/nginx-logs:/etc/nginx/logs
    expose:
      - 80
    environment:
      VIRTUAL_HOST: ch.ckl.st
      LETSENCRYPT_HOST: ch.ckl.st
      LETSENCRYPT_EMAIL: pablo@qecept.com
networks:
  default:
    external:
      name: nginx-proxy
